
-- Existing Users Table
CREATE TABLE "Users" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR,
    email VARCHAR UNIQUE NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    password_hash VARCHAR NOT NULL,
    phone_number VARCHAR,
    latitude FLOAT,
    longitude FLOAT,
    address VARCHAR
);

-- Existing Restaurants Table
CREATE TABLE "Restaurants" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    phone_number VARCHAR NOT NULL,
    description TEXT
);

-- Updated MenuItems Table with Additional Rating Columns
CREATE TABLE "MenuItems" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT REFERENCES "Restaurants"(id),
    name VARCHAR NOT NULL,
    image VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    description TEXT,
    price INT NOT NULL
);

-- Existing Bookings Table
CREATE TABLE "Bookings" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES "Users"(id),
    restaurant_id INT REFERENCES "Restaurants"(id),
    booking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Existing Orders Table
CREATE TABLE "Orders" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INT REFERENCES "Bookings"(id),
    menu_item_id INT REFERENCES "MenuItems"(id),
    quantity INT NOT NULL
);

-- New Ratings Table for Menu Items
CREATE TABLE "MenuItemRatings" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id INT REFERENCES "MenuItems"(id),
    user_id INT REFERENCES "Users"(id),
    rating INT CHECK (rating >= 1 AND rating <= 5),  -- Assuming rating is on a scale of 1 to 5
    review TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
